env:
  global:
    - DOCKER_IMAGE=tstenner/manylinux:gcc9.1.0
    # directory containing the project source
    - REPO_DIR=.
    # pip dependencies to _test_ project
    - TEST_DEPENDS="tox"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - TWINE_USERNAME="anthrotype"
    - secure: O0cS/1sCRfjuDVdlMihyqyX6b7so3qZ41OhqDC5O5f4bvk87vno9GGk7U0ZfdoUqjnjXLd7QvEnax4vWJx/tvSEh/wJC07U2pcFDNehkYJIEZCf/MQWzESWd905fUSWP1/BbKgCWvfq7WZOH/3iKpDyQP5DKlrnoq3E2H2gYR3xKd7ASAZHtUYariE4bMEnjg4SDANfm7SHnlD5a/S4/IjgxU0DjCKKbkX7HbGUiCAjjr3j3z9amAhxCmoWyOKvNHjKegG2okEb08ERtcbyYWan0Eu5FqCDMkWwhQmACC1lXz0xHyHW4VZWDyQC1cDrSTirN9rNdamTnfqJPP1eURxGNmNqazrem77HAUKIuh5WjXLFZwKzp+KWMb5TTXYWIsh8gx/IAjGfPoi8nKOWd+bxWLeakDM4kka7pLJDsuRnWSWKzDaDDpMuFm76RzDJjTWCsva93l3EZ8/fkXQ3sGrVC7f8MAjaqBEs+vV6YZMv3WZuSfZkv2AVoPLKkPxWB3RDekKjAw/O8qovqDSGHVgV8XU+6AQVEWhEu8dEtEbXn0UPMQ/bSjQeugl5AkmmBC4iIisuP8rtPB+xdV/iQALEM/RdLJHzC76VQNuXMke69roK5+ZhA6TCCix7I3TIq+XtNQ78SnAUGuooND+WHxVVSQ5GK9DGiCMetRlOQkIA=

language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - BUILD_SDIST=true
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
        - MB_PYTHON_OSX_VER=10.9
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_PYTHON_OSX_VER=10.9
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.9

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_wheel $REPO_DIR $PLAT

script:
  - install_run $PLAT

after_success:
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "fonttools/skia-pathops" ]; then
      pip install --upgrade twine
      twine upload wheelhouse/skia_pathops*.whl
      if [ "$BUILD_SDIST" == true ]; then
        pip install --upgrade setuptools setuptools_scm
        python setup.py --quiet sdist --dist-dir dist
        twine upload dist/skia-pathops*.zip
      fi
    fi
