name: Build + Deploy

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest]
        platform: [x64]
    env:
      REPO_DIR: "."
      PLAT: "x86_64"
      UNICODE_WIDTH: 32
      MB_ML_VER: 2014
      TEST_DEPENDS: "tox"
      MB_PYTHON_VERSION: ${{ matrix.python-version }}
      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }}
      BUILD_SKIA_FROM_SOURCE: 0
      SKIA_LIBRARY_DIR: "build/download"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up environment variables
      run: |
        if [ "macos-latest" == "${{ matrix.os }}" ]; then
          echo "TRAVIS_OS_NAME=osx" >> $GITHUB_ENV
        else
          echo "TRAVIS_OS_NAME=ubuntu" >> $GITHUB_ENV
        fi
        echo "export BUILD_SKIA_FROM_SOURCE=${BUILD_SKIA_FROM_SOURCE}" >> env_vars.sh
        echo "export SKIA_LIBRARY_DIR=${SKIA_LIBRARY_DIR}" >> env_vars.sh
    - name: Install virtualenv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Download pre-compiled libskia
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if [ "$BUILD_SKIA_FROM_SOURCE" == "0" ]; then
          pip install githubrelease
          python ci/download_libskia.py -d "${SKIA_LIBRARY_DIR}"
        fi
    - name: Build and Install Wheels
      run: |
        source multibuild/common_utils.sh
        source multibuild/travis_steps.sh
        echo "------- BEFORE INSTALL --------"
        before_install
        echo "------- BUILD WHEEL --------"
        build_wheel $REPO_DIR $PLAT
        echo "------- INSTALL_RUN --------"
        install_run $PLAT
    - uses: actions/upload-artifact@v2
      with:
        name: skia_pathops-${{ env.TRAVIS_OS_NAME }}-${{ matrix.python-version }}
        path: wheelhouse/*.whl
